### ISSUE TITLE
Project does not start with Starcounter 2.1.177

### ISSUE THREAD

**Issue by warpech** [handsoncode-apps/Basket#2]
Perhaps something wrong with my setup (Starcounter 2.1.177).

Trying to start BasketDemoApp in VS2015 gives the following exception on startup:

```
ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 6066.
Arguments=--nocache --maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave "C:\www\handsoncode-apps\BasketDemoApp\Basket\bin\Debug\BasketDemo.exe" --outdir="c:\db\Personal\Temp\default\default-20151023T193913965\weaver\20A9575A61F476C59D9690692FED1A01EA44FA7F"
Output:
A4A7D6FA-EB34-442A-B579-DBB1DBB859E3System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.1.177.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Internal.Weaver.BackingInfrastructure.TypeSpecificationEmit.GetColumnHandle(String typeNameDeclaring, String fieldName) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Internal.Weaver\BackingInfrastructure\TypeSpecificationEmit.cs:line 163
   at Starcounter.Internal.Weaver.ScTransformTask.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Internal.Weaver\ScTransformTask.cs:line 227
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeaver.cs:line 316
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeaver.cs:line 224
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 205
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 154
   at Starcounter.Weaver.Program.Main(String[] args) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 36
   --- End of inner exception stack trace ---A4A7D6FA-EB34-442A-B579-DBB1DBB859E3
System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.1.177.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Internal.Weaver.BackingInfrastructure.TypeSpecificationEmit.GetColumnHandle(String typeNameDeclaring, String fieldName) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Internal.Weaver\BackingInfrastructure\TypeSpecificationEmit.cs:line 163
   at Starcounter.Internal.Weaver.ScTransformTask.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Starcounter.Internal.Weaver\ScTransformTask.cs:line 227
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeaver.cs:line 316
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\CodeWeaver.cs:line 224
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 205
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 154
   at Starcounter.Weaver.Program.Main(String[] args) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\scweaver\Program.cs:line 36
   --- End of inner exception stack trace ---

Version: 2.1.177.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030.
```

@jakubklekota what version of Starcounter and VS are you using?

@miyconst does it start for you?

**Comment by miyconst** [comment]
@warpech, did you set `false` to copy local for the simplified reference?

**Comment by miyconst** [comment]
And did you rebuild @jakubklekota's branch of simplified before starting Starcounter server?

**Comment by warpech** [comment]
Yes, I did both.

After I deleted my databases and installed Starcounter 2.1.397 it started to work. I am not sure which one fixed this.

**Comment by warpech** [comment]
After reverting to Starcounter 2.1.177 I get the same problem again. So it must be some breaking change in Starcounter that is used by the app. 

Waiting for @jakubklekota to provide the Starcounter version number he is using.

**Comment by jakubklekota** [comment]
@warpech give me few minutes I try fix the bug.

**Comment by jakubklekota** [comment]
@warpech Do you try... On first step download the simplify data model from handsoncode-app/simplify, stop the starcounter, clean this project, build this project. In VS output show the new dll was copy to the localization "C:\Program Files\Starcounter\Public Assemblies\Simplified.Data.Model.dll", then open BasketDemoApp, rebuild and then start the app. When I reinstall starcounter database I has the same problem.

Now BasketDemoApp work fine.

**Comment by warpech** [comment]
As said above, I already tried that.

What version of Starcounter and VS are you using?

**Comment by jakubklekota** [comment]
VS2013

**Comment by warpech** [comment]
The problem with this issue is not that BasketDemoApp does not build. The problem is that it only builds with a nightly build and not with a stable release (Starcounter 2.1.177).

**Comment by jakubklekota** [comment]
@warpech BasketDemoApp working with starcounter 2.1.177 in my enviroment.

**Comment by jakubklekota** [comment]
@warpech coud you creating new branch and pull your solution to this branch ?

**Comment by warpech** [comment]
Builds now. Closing
